### ISSUE TITLE
Track open rate for HTML emails?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/email#1]
As a data-driven product owner/manager/developer
I want the  ability to track open rates for emails 
So that I know that the emails I am sending are being read.

# Todo

+ [x] Repurpose the code from Hits https://github.com/dwyl/hits 
+ [x] Create endpoint for tracking 
  + [x] Get request should include unique identifier
  + [x] Unique identifier should be stored in the DB and sent to Lambda so it can be included in the template that gets sent.

**Comment by nelsonic** [comment]
Possibly use Google Analytics: http://dyn.com/blog/tracking-email-opens-via-google-analytics/ ?

**Comment by nelsonic** [comment]
Solution: https://www.campaignmonitor.com/blog/email-marketing/2010/06/adding-background-images-to-your-email-in-two-simple-steps/

**Comment by nelsonic** [comment]
I acknowledge that email tracking can be seen as an erosion of privacy 
if the data ends up in the wrong hands or is used for nefarious purposes:
https://www.wired.com/story/how-email-open-tracking-quietly-took-over-the-web

Our sole intention is to track if our communications are effective.
Our objective is to build a great product and we need to know people are engaging in feedback.
We _definitely_ won't be sending pointless vanity emails the way most "social networks" do to force people to click to then spend hours on their [irredeemable](https://youtu.be/pPWhpXRYzNg?t=79) time suck.

If people aren't _receiving_ our emails then we have no way of knowing if what we are doing is working.
If people aren't _opening_ our emails then we know we are either sending too many or they aren't _relevant_ to the recipients.

**Comment by nelsonic** [comment]
Open rate tracking working:
![image](https://user-images.githubusercontent.com/194400/77212286-7bd4c300-6afe-11ea-9716-8aba7daeb306.png)

**Comment by nelsonic** [comment]
Try it: https://phemail.herokuapp.com/

**Comment by nelsonic** [comment]
Made a quick video of the demo of open tracking working: https://youtu.be/yflPSotYd9Y

![send-email-dashboard-test](https://user-images.githubusercontent.com/194400/77336873-0d6f4b00-6d20-11ea-8cb1-510d22a69385.gif)

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/77356364-0bb48000-6d3e-11ea-952a-ecd862ec66e0.png)
