### ISSUE TITLE
Display Email Address in Dashboard?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/email#32]
At present the dashboard displays the status of emails: https://dwylmail.herokuapp.com
![image](https://user-images.githubusercontent.com/194400/78156739-1a362200-7437-11ea-8030-c8dff12c0392.png)

This is _much_ better than zero visibility. But it's not _actionable_. 
We need to be able to click on an item to see the email address so we know exactly what went wrong.
In order to view an email address we need Auth to ensure privacy.

## Todo

+ [ ] Enable Auth for the Email App once the `DWYL_API_KEY` feature is shipped https://github.com/dwyl/auth/issues/42
+ [ ] Make the each row of the dashboard clickable. 
+ [ ] Render the "show" view including the decrypted email address if the requestor is authorised to see it.
