### ISSUE TITLE
Chore: Migrate Email Dashboard from Heroku to Fly.io

### ISSUE THREAD

**Issue by nelsonic** [dwyl/email#61]
Migrate email dashboard from Heroku to Fly.io? https://dwylmail.herokuapp.com/
![image](https://user-images.githubusercontent.com/194400/198866976-598add90-163f-43f2-9fea-8b472602c6f5.png)

related to: https://github.com/dwyl/learn-heroku/issues/52

# Todo

+ [ ] Backup Environment variables see: https://github.com/dwyl/learn-heroku/issues/35
+ [ ] Create PR to capture work
+ [ ] Setup auto-deploy for Fly.io
+ [ ] Manually deploy to confirm everything working

**Comment by nelsonic** [comment]
**`$16/month`** is the _lowest_ we would pay to run this ultra-low volume/overhead App on `Heroku`:
https://www.heroku.com/pricing
<img width="1481" alt="image" src="https://user-images.githubusercontent.com/194400/218251800-9d70e232-99e5-4d07-8ab2-4da9d383e5c6.png">

For that I would prefer to pay `Keila` who have a _much_ more advanced Email Drafting, Sending & Tracking App https://github.com/dwyl/email/issues/60

**Comment by nelsonic** [comment]
https://dashboard.heroku.com/apps/dwylmail
<img width="1428" alt="dwylmail-heroku-fail" src="https://user-images.githubusercontent.com/194400/218252051-ff9e1e2d-4a0e-4aba-9823-5ae6aa58db41.png">

As you can see, `Heroku` kindly already deleted all our data:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/194400/218252368-5a3dd560-423e-40d6-a548-5bccaba5734f.png">

So even if we _wanted_ to pay `Salesforce` **`$16/month`** to host this for us ... we'd be starting from scratch. 🤦‍♂️ 

Going to **`try`** and re-boot this ...

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/194400/218252442-e7961fee-6e78-4b52-aaef-8c0d54e7a845.png">

https://dashboard.heroku.com/apps/dwylmail/resources/new?addonService=heroku-postgresql
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/194400/218252452-c294684e-9f5a-411e-bc38-fb8f10152e9b.png">

https://dwylmail.herokuapp.com/
<img width="907" alt="image" src="https://user-images.githubusercontent.com/194400/218252515-fa2c85c8-418d-4b30-a361-7ed265d72b05.png">

Restart all dynos ... ⏳ 

<img width="704" alt="image" src="https://user-images.githubusercontent.com/194400/218252615-ba51c3da-fbe5-4733-8656-553d839ac556.png">

Yah! 🎉 

https://dashboard.heroku.com/apps/dwylmail/logs 
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/194400/218252656-1a88a37e-9fc8-44db-808b-29b4979a7b3a.png">

Useless.

**Comment by nelsonic** [comment]
Just tried to run this on `localhost` with `Elixir 1.14.3` and got _hundreds_ of warnings! 😖 

Tried running: `mix ecto.reset` got:
```sh
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:8

warning: use Mix.Config is deprecated. Use the Config module instead
  config/dev.exs:1

The database for App.Repo has been dropped
The database for App.Repo has been created

10:18:52.527 [info] == Running 20191113100513 App.Repo.Migrations.CreateTags.change/0 forward

10:18:52.529 [info] create table tags

10:18:52.533 [info] == Migrated 20191113100513 in 0.0s

10:18:52.549 [info] == Running 20191113100912 App.Repo.Migrations.CreateStatus.change/0 forward

10:18:52.549 [info] create table status

10:18:52.551 [info] == Migrated 20191113100912 in 0.0s

10:18:52.552 [info] == Running 20191113100920 App.Repo.Migrations.CreatePeople.change/0 forward

10:18:52.552 [info] create table people

10:18:52.556 [info] create index people_status_index

10:18:52.557 [info] create index people_tag_index

10:18:52.558 [info] == Migrated 20191113100920 in 0.0s

10:18:52.560 [info] == Running 20191113114340 App.Repo.Migrations.AddPersonIdToTag.change/0 forward

10:18:52.560 [info] alter table tags

10:18:52.560 [info] == Migrated 20191113114340 in 0.0s

10:18:52.561 [info] == Running 20191113141229 App.Repo.Migrations.AddPersonIdToStatus.change/0 forward

10:18:52.561 [info] alter table status

10:18:52.566 [info] == Migrated 20191113141229 in 0.0s

10:18:52.567 [info] == Running 20191130210036 App.Repo.Migrations.AddPictureLocaleToPeople.change/0 forward

10:18:52.567 [info] alter table people

10:18:52.568 [info] == Migrated 20191130210036 in 0.0s

10:18:52.570 [info] == Running 20200224224024 App.Repo.Migrations.CreateSent.change/0 forward

10:18:52.570 [info] create table sent

10:18:52.574 [info] create index sent_person_id_index

10:18:52.575 [info] create index sent_status_id_index

10:18:52.576 [info] == Migrated 20200224224024 in 0.0s
MacOSX 10.7 or later required for --file-events
[notice] Application app exited: App.Application.start(:normal, []) returned an error: shutdown: failed to start child: AppWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2
        ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2Server
            ** (EXIT) an exception was raised:
                ** (UndefinedFunctionError) function :pg2.create/1 is undefined or private
                    (kernel 8.5.3) :pg2.create({:phx, App.PubSub})
                    (phoenix_pubsub 1.1.2) lib/phoenix/pubsub/pg2_server.ex:43: Phoenix.PubSub.PG2Server.init/1
                    (stdlib 4.2) gen_server.erl:851: :gen_server.init_it/2
                    (stdlib 4.2) gen_server.erl:814: :gen_server.init_it/6
                    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
[notice] Application phoenix_live_view exited: :stopped
[notice] Application hackney exited: :stopped
[notice] Application metrics exited: :stopped
[notice] Application ssl_verify_fun exited: :stopped
[notice] Application certifi exited: :stopped
[notice] Application mimerl exited: :stopped
[notice] Application idna exited: :stopped
[notice] Application unicode_util_compat exited: :stopped
[notice] Application poison exited: :stopped
[notice] Application ex_aws_lambda exited: :stopped
[notice] Application ex_aws exited: :stopped
[notice] Application joken exited: :stopped
[notice] Application jose exited: :stopped
[notice] Application fields exited: :stopped
[notice] Application html_sanitize_ex exited: :stopped
[notice] Application mochiweb exited: :stopped
[notice] Application syntax_tools exited: :stopped
[notice] Application xmerl exited: :stopped
[notice] Application argon2_elixir exited: :stopped
[notice] Application comeonin exited: :stopped
[notice] Application plug_cowboy exited: :stopped
[notice] Application cowboy exited: :stopped
[notice] Application ranch exited: :stopped
[notice] Application cowlib exited: :stopped
[notice] Application jason exited: :stopped
[notice] Application phoenix_live_reload exited: :stopped
[notice] Application file_system exited: :stopped
[notice] Application phoenix_html exited: :stopped
[notice] Application phoenix_ecto exited: :stopped
[notice] Application runtime_tools exited: :stopped
** (Mix) Could not start application app: App.Application.start(:normal, []) returned an error: shutdown: failed to start child: AppWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2
        ** (EXIT) shutdown: failed to start child: Phoenix.PubSub.PG2Server
            ** (EXIT) an exception was raised:
                ** (UndefinedFunctionError) function :pg2.create/1 is undefined or private
                    (kernel 8.5.3) :pg2.create({:phx, App.PubSub})
                    (phoenix_pubsub 1.1.2) lib/phoenix/pubsub/pg2_server.ex:43: Phoenix.PubSub.PG2Server.init/1
                    (stdlib 4.2) gen_server.erl:851: :gen_server.init_it/2
                    (stdlib 4.2) gen_server.erl:814: :gen_server.init_it/6
                    (stdlib 4.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```

**Comment by nelsonic** [comment]
This is going to require _way_ too much effort to update. 
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/194400/218253084-6b69eaa7-76fb-4b5e-b4a8-9d65e6d5e6f1.png">

Deleted the `postgres` instance and shut down the dyno. RIP `Heroku`. 💀

**Comment by nelsonic** [comment]
I've poured enough time into attempting to revive this project ... ⏳ 
<img width="896" alt="image" src="https://user-images.githubusercontent.com/194400/218253422-08b9fc73-895d-4b52-8a78-77af782b71f0.png">

Just going to cut my losses and move on!

**Comment by nelsonic** [comment]
Even if we _wanted_ to use `Heroku` ... we would be _forced_ to upgrade the stack in a few months:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/194400/218253546-1ecfb4fa-8782-4282-a25e-e10f6375c70f.png">

```
The Heroku-18 stack is deprecated
This app is using the Heroku-18 stack, which is deprecated. 
From April 30th, 2023, Heroku-18 will be end-of-life 
and no longer receive security updates. 
From May 1st, 2023, builds will be disabled. 
Please upgrade your app to a newer Heroku stack. 
[ Visit here to learn more](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq)
```

That would mean updating the `email` app to use latest `Elixir` 
and then all the warnings noted above https://github.com/dwyl/email/issues/61#issuecomment-1426686495 ⬆️ 
would be a consistent source of pain.

So the only option would be to manually upgrade the App to `Phoenix 1.6.X` which is _already_ out-of-date. ⏳

**Comment by nelsonic** [comment]
Just googled for "Send Email Phoenix" (incognito) and the second result is: 
https://github.com/dwyl/learn-phoenix-framework/blob/master/sending-emails.md

<img width="674" alt="image" src="https://user-images.githubusercontent.com/194400/218254926-2658a14f-c7ee-4c10-a74c-b68e0afe2092.png">


# `#SEOMasterPlan` 🤯 

Need to update it so we don't waste people's time. ⏳

**Comment by nelsonic** [comment]
Tried again on `localhost` just to make sure I wasn't going crazy ... 

<img width="1193" alt="image" src="https://github.com/dwyl/email/assets/194400/6032577c-3754-497b-bc40-022a048abf30">

SSL error: 
```
==> ssl_verify_fun
Compiling 7 files (.erl)
src/ssl_verify_fun_cert_helpers.erl:13:14: can't find include lib "public_key/include/public_key.hrl"
%   13| -include_lib("public_key/include/public_key.hrl").
%     |              ^
```

Similar to: https://github.com/dwyl/elixir-invoke-lambda-example/issues/30
i.e. `OTP` has made a breaking change that means our older Apps fail.

**Comment by nelsonic** [comment]
Reading: https://elixirforum.com/t/ubuntu-20-04-compile-ssl-verify-fun-fails/32802
The solution appears to be to install `erlang-dev` ... but that's on `Ubuntu` ... 
Googled: https://www.google.com/search?q=erlang-dev+mac
Reading: https://dev.to/zacky1972/perfect-steps-of-installalling-erlang-and-elixir-to-apple-silicon-mac-2021-dec-edition-4iae 👀

**Comment by nelsonic** [comment]
That was a dead end (way too many steps and not well explained ...)
Reading: https://devheroes.io/en/erlang-elixir-macos-m1/

**Comment by nelsonic** [comment]
There are a _lot_ of steps ... this shouldn't be this complicated!! 😢

**Comment by nelsonic** [comment]
Following: https://github.com/elixir-lang/elixir/issues/12681#issuecomment-1598312912
